apiVersion: v1
kind: Service
metadata:
  name: {{ include "greeting-app.name" . }}-service
  labels:
    {{- include "greeting-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.target }}
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    {{- include "greeting-app.selectorLabels" . | nindent 4 }}
