apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greeting-ingress
  namespace: flask-apps
spec:
  rules:
#    - host: localhost
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: greeting-service
              port:
                number: 5000

